In [ ]:
!pip install pandas pyarrow -q

Opening the parquet file

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving team_4.parquet to team_4.parquet

In [ ]:
import pandas as pd
from pathlib import Path

INPUT_FILE = "team_4.parquet"
df = pd.read_parquet(INPUT_FILE)

print(f"Loaded {len(df):,} rows  x  {df.shape[1]} columns")
df.head()

Loaded 5,831,431 rows  x  22 columns

,station_id,state,city,station_name,timestamp,datetime,at_c,rh_percent,ws_m_s,wd_deg,...,sr_w_mt2,bp_mmhg,vws_m_s,pollutant,value,station,year,month,day,hour
0,site_5024,Delhi,Delhi,"Alipur, Delhi - DPCC",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,8.2,76.00,NaN,72.90,...,3.8,973.7,NaN,benzene,2.10,"Alipur, Delhi - DPCC",2024,1,1,0
1,site_103,Delhi,Delhi,"CRRI Mathura Road, Delhi - IMD",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,no2,19.40,"CRRI Mathura Road, Delhi - IMD",2024,1,1,0
2,site_103,Delhi,Delhi,"CRRI Mathura Road, Delhi - IMD",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,no,39.17,"CRRI Mathura Road, Delhi - IMD",2024,1,1,0
3,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,93.12,0.72,39.64,...,NaN,NaN,NaN,benzene,0.22,"DTU, Delhi - CPCB",2024,1,1,0
4,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,93.12,0.72,39.64,...,NaN,NaN,NaN,co,0.90,"DTU, Delhi - CPCB",2024,1,1,0

In [ ]:
print("Columns:", list(df.columns))
print()
print(df.dtypes)

Columns: ['station_id', 'state', 'city', 'station_name', 'timestamp', 'datetime', 'at_c', 'rh_percent', 'ws_m_s', 'wd_deg', 'rf_mm', 'tot_rf_mm', 'sr_w_mt2', 'bp_mmhg', 'vws_m_s', 'pollutant', 'value', 'station', 'year', 'month', 'day', 'hour']

station_id                   object
state                        object
city                         object
station_name                 object
timestamp                    object
datetime        datetime64[us, UTC]
at_c                        float64
rh_percent                  float64
ws_m_s                      float64
wd_deg                      float64
rf_mm                       float64
tot_rf_mm                   float64
sr_w_mt2                    float64
bp_mmhg                     float64
vws_m_s                     float64
pollutant                    object
value                       float64
station                      object
year                          int32
month                         int32
day                           int32
hour                          int32
dtype: object

In [ ]:
print("=" * 60)
print("INGESTION SUMMARY")
print("=" * 60)

print(f"Total records      : {len(df):,}")
print(f"Columns            : {df.shape[1]}")
print(f"Date range         : {df['datetime'].min()}  →  {df['datetime'].max()}")
print(f"Years              : {sorted(df['year'].unique().tolist())}")
print(f"Months             : {sorted(df['month'].unique().tolist())}")
print(f"States             : {df['state'].nunique()}  → {list(df['state'].unique())}")
print(f"Cities             : {df['city'].nunique()}  → {list(df['city'].unique())}")
print(f"Stations           : {df['station_id'].nunique()}")
print(f"Pollutant species  : {df['pollutant'].nunique()}")
print(f"   {sorted(df['pollutant'].unique().tolist())}")

============================================================
INGESTION SUMMARY
============================================================
Total records      : 5,831,431
Columns            : 22
Date range         : 2024-01-01 00:00:00+00:00  →  2025-12-31 23:45:00+00:00
Years              : [2024, 2025]
Months             : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
States             : 1  → ['Delhi']
Cities             : 1  → ['Delhi']
Stations           : 10
Pollutant species  : 13
   ['benzene', 'co', 'eth_benzene', 'mp_xylene', 'nh3', 'no', 'no2', 'ozone', 'pm10', 'pm25', 'so2', 'toluene', 'xylene']

In [ ]:
df.groupby("year").size()

year
2024    2880045
2025    2951386
dtype: int64

In [ ]:
df.groupby(["year", "month"]).size()

year  month
2024  1        226196
      2        221832
      3        237908
      4        235758
      5        250679
      6        231249
      7        251189
      8        241789
      9        227096
      10       248042
      11       251541
      12       256766
2025  1        253498
      2        228545
      3        255675
      4        246050
      5        255187
      6        242426
      7        245173
      8        247729
      9        231718
      10       253204
      11       246998
      12       245183
dtype: int64

In [ ]:
df["pollutant"].value_counts()

pollutant
pm10           642383
no2            637561
co             634509
ozone          629925
pm25           628001
no             617615
benzene        440298
nh3            440094
so2            429562
toluene        387390
mp_xylene      126576
eth_benzene    124814
xylene          92703
Name: count, dtype: int64

In [ ]:
df.isna().sum().sort_values(ascending=False)

vws_m_s         5831431
ws_m_s          2540853
sr_w_mt2        2213776
at_c            1990984
bp_mmhg         1950992
rf_mm           1941815
wd_deg          1529016
rh_percent      1403566
datetime              0
timestamp             0
state                 0
station_id            0
station_name          0
city                  0
tot_rf_mm             0
pollutant             0
value                 0
station               0
year                  0
month                 0
day                   0
hour                  0
dtype: int64

In [ ]:
summary_lines = [
    f"Total records      : {len(df):,}",
    f"Columns            : {df.shape[1]}",
    f"Date range         : {df['datetime'].min()}  →  {df['datetime'].max()}",
    f"Years              : {sorted(df['year'].unique().tolist())}",
    f"Stations           : {df['station_id'].nunique()}",
    f"Pollutant species  : {df['pollutant'].nunique()}",
    "",
    "Records per year-month:",
    df.groupby(["year", "month"]).size().to_string(),
    "",
    "Records per pollutant:",
    df["pollutant"].value_counts().to_string(),
]
Path("ingestion_summary.txt").write_text("\n".join(summary_lines))
print("✓ Saved ingestion_summary.txt")

✓ Saved ingestion_summary.txt

In [ ]:
OUTPUT_DIR = Path("partitioned_data")
OUTPUT_DIR.mkdir(exist_ok=True)

written = 0
for (yr, mo), chunk in df.groupby(["year", "month"]):
    folder = OUTPUT_DIR / f"year={yr}" / f"month={mo:02d}"
    folder.mkdir(parents=True, exist_ok=True)
    out_path = folder / "data.parquet"
    chunk.to_parquet(out_path, index=False)
    written += 1
    print(f"  year={yr} month={mo:02d}  →  {len(chunk):>8,} rows")

print(f"\n✓ Wrote {written} partition files into '{OUTPUT_DIR}/'")

  year=2024 month=01  →   226,196 rows
  year=2024 month=02  →   221,832 rows
  year=2024 month=03  →   237,908 rows
  year=2024 month=04  →   235,758 rows
  year=2024 month=05  →   250,679 rows
  year=2024 month=06  →   231,249 rows
  year=2024 month=07  →   251,189 rows
  year=2024 month=08  →   241,789 rows
  year=2024 month=09  →   227,096 rows
  year=2024 month=10  →   248,042 rows
  year=2024 month=11  →   251,541 rows
  year=2024 month=12  →   256,766 rows
  year=2025 month=01  →   253,498 rows
  year=2025 month=02  →   228,545 rows
  year=2025 month=03  →   255,675 rows
  year=2025 month=04  →   246,050 rows
  year=2025 month=05  →   255,187 rows
  year=2025 month=06  →   242,426 rows
  year=2025 month=07  →   245,173 rows
  year=2025 month=08  →   247,729 rows
  year=2025 month=09  →   231,718 rows
  year=2025 month=10  →   253,204 rows
  year=2025 month=11  →   246,998 rows
  year=2025 month=12  →   245,183 rows

✓ Wrote 24 partition files into 'partitioned_data/'

In [ ]:
!find partitioned_data -type f | sort | head -30

partitioned_data/year=2024/month=01/data.parquet
partitioned_data/year=2024/month=02/data.parquet
partitioned_data/year=2024/month=03/data.parquet
partitioned_data/year=2024/month=04/data.parquet
partitioned_data/year=2024/month=05/data.parquet
partitioned_data/year=2024/month=06/data.parquet
partitioned_data/year=2024/month=07/data.parquet
partitioned_data/year=2024/month=08/data.parquet
partitioned_data/year=2024/month=09/data.parquet
partitioned_data/year=2024/month=10/data.parquet
partitioned_data/year=2024/month=11/data.parquet
partitioned_data/year=2024/month=12/data.parquet
partitioned_data/year=2025/month=01/data.parquet
partitioned_data/year=2025/month=02/data.parquet
partitioned_data/year=2025/month=03/data.parquet
partitioned_data/year=2025/month=04/data.parquet
partitioned_data/year=2025/month=05/data.parquet
partitioned_data/year=2025/month=06/data.parquet
partitioned_data/year=2025/month=07/data.parquet
partitioned_data/year=2025/month=08/data.parquet
partitioned_data/year=2025/month=09/data.parquet
partitioned_data/year=2025/month=10/data.parquet
partitioned_data/year=2025/month=11/data.parquet
partitioned_data/year=2025/month=12/data.parquet

In [ ]:
df_jan_2024 = pd.read_parquet("partitioned_data/year=2024/month=01/data.parquet")
print(f"Jan 2024 partition: {len(df_jan_2024):,} rows")
df_jan_2024.head()

Jan 2024 partition: 226,196 rows

,station_id,state,city,station_name,timestamp,datetime,at_c,rh_percent,ws_m_s,wd_deg,...,sr_w_mt2,bp_mmhg,vws_m_s,pollutant,value,station,year,month,day,hour
0,site_5024,Delhi,Delhi,"Alipur, Delhi - DPCC",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,8.2,76.00,NaN,72.90,...,3.8,973.7,NaN,benzene,2.10,"Alipur, Delhi - DPCC",2024,1,1,0
1,site_103,Delhi,Delhi,"CRRI Mathura Road, Delhi - IMD",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,no2,19.40,"CRRI Mathura Road, Delhi - IMD",2024,1,1,0
2,site_103,Delhi,Delhi,"CRRI Mathura Road, Delhi - IMD",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,no,39.17,"CRRI Mathura Road, Delhi - IMD",2024,1,1,0
3,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,93.12,0.72,39.64,...,NaN,NaN,NaN,benzene,0.22,"DTU, Delhi - CPCB",2024,1,1,0
4,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,93.12,0.72,39.64,...,NaN,NaN,NaN,co,0.90,"DTU, Delhi - CPCB",2024,1,1,0

In [ ]:
import shutil
OUTPUT_DIR = Path("partitioned_data")

# wipe the old broken output
if OUTPUT_DIR.exists():
    shutil.rmtree(OUTPUT_DIR)
OUTPUT_DIR.mkdir()

written = 0
for (yr, mo), chunk in df.groupby(["year", "month"]):
    folder = OUTPUT_DIR / f"year={yr}" / f"month={mo:02d}"
    folder.mkdir(parents=True, exist_ok=True)
    # drop year/month from the data — they're encoded in the folder path
    chunk.drop(columns=["year", "month"]).to_parquet(folder / "data.parquet", index=False)
    written += 1
    print(f"  year={yr} month={mo:02d}  →  {len(chunk):>8,} rows")

print(f"\n✓ Wrote {written} partition files into '{OUTPUT_DIR}/'")

  year=2024 month=01  →   226,196 rows
  year=2024 month=02  →   221,832 rows
  year=2024 month=03  →   237,908 rows
  year=2024 month=04  →   235,758 rows
  year=2024 month=05  →   250,679 rows
  year=2024 month=06  →   231,249 rows
  year=2024 month=07  →   251,189 rows
  year=2024 month=08  →   241,789 rows
  year=2024 month=09  →   227,096 rows
  year=2024 month=10  →   248,042 rows
  year=2024 month=11  →   251,541 rows
  year=2024 month=12  →   256,766 rows
  year=2025 month=01  →   253,498 rows
  year=2025 month=02  →   228,545 rows
  year=2025 month=03  →   255,675 rows
  year=2025 month=04  →   246,050 rows
  year=2025 month=05  →   255,187 rows
  year=2025 month=06  →   242,426 rows
  year=2025 month=07  →   245,173 rows
  year=2025 month=08  →   247,729 rows
  year=2025 month=09  →   231,718 rows
  year=2025 month=10  →   253,204 rows
  year=2025 month=11  →   246,998 rows
  year=2025 month=12  →   245,183 rows

✓ Wrote 24 partition files into 'partitioned_data/'

In [ ]:
df_all = pd.read_parquet("partitioned_data/")
print(f"Total reloaded: {len(df_all):,} rows")
df_all.head()

Total reloaded: 5,831,431 rows

,station_id,state,city,station_name,timestamp,datetime,at_c,rh_percent,ws_m_s,wd_deg,...,sr_w_mt2,bp_mmhg,vws_m_s,pollutant,value,station,day,hour,year,month
0,site_5024,Delhi,Delhi,"Alipur, Delhi - DPCC",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,8.2,76.00,NaN,72.90,...,3.8,973.7,NaN,benzene,2.10,"Alipur, Delhi - DPCC",1,0,2024,1
1,site_103,Delhi,Delhi,"CRRI Mathura Road, Delhi - IMD",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,no2,19.40,"CRRI Mathura Road, Delhi - IMD",1,0,2024,1
2,site_103,Delhi,Delhi,"CRRI Mathura Road, Delhi - IMD",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,no,39.17,"CRRI Mathura Road, Delhi - IMD",1,0,2024,1
3,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,93.12,0.72,39.64,...,NaN,NaN,NaN,benzene,0.22,"DTU, Delhi - CPCB",1,0,2024,1
4,site_118,Delhi,Delhi,"DTU, Delhi - CPCB",2024-01-01T00:00:00.000000+0000,2024-01-01 00:00:00+00:00,NaN,93.12,0.72,39.64,...,NaN,NaN,NaN,co,0.90,"DTU, Delhi - CPCB",1,0,2024,1

In [ ]:
!zip -r partitioned_data.zip partitioned_data/ -q
from google.colab import files
files.download("partitioned_data.zip")